version: '3.9'
services:
  db:
    image: postgis/postgis:latest
    restart: always
    environment:
      POSTGRES_DB: charitywalk_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
    ports:
      - "5434:5432"
